# seguindo o tutorial desse site
# http://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/

CC = gcc
CFLAGS = -Wall -g -I.

queue: queue.o testafila.o
	$(CC) -o teste queue.c testafila.c

clean:
	rm *.o teste
